In [1]:
import numpy as np

In [5]:
n1=np.arange(10*10).reshape((10,10))
n1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [8]:
# n1[start:end:step,start:end:step]
n1[2:10:2,3:9:2]

array([[23, 25, 27],
       [43, 45, 47],
       [63, 65, 67],
       [83, 85, 87]])

In [10]:
n1[3:10,2:8]

array([[32, 33, 34, 35, 36, 37],
       [42, 43, 44, 45, 46, 47],
       [52, 53, 54, 55, 56, 57],
       [62, 63, 64, 65, 66, 67],
       [72, 73, 74, 75, 76, 77],
       [82, 83, 84, 85, 86, 87],
       [92, 93, 94, 95, 96, 97]])

In [29]:
n1[-8:-2,-6:-1]

array([[24, 25, 26, 27, 28],
       [34, 35, 36, 37, 38],
       [44, 45, 46, 47, 48],
       [54, 55, 56, 57, 58],
       [64, 65, 66, 67, 68],
       [74, 75, 76, 77, 78]])

In [30]:
n1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

## Fancy Slicing

In [35]:
n2=np.arange(10).reshape(10)
n2
n2[0:5]

array([0, 1, 2, 3, 4])

In [42]:
n2[[False,True,False,False,False,False,False,False,False,True]]

array([1, 9])

## Conditional Slicing

In [46]:
(n2==7)|(n2==1)

array([False,  True, False, False, False, False, False,  True, False,
       False])

In [48]:
a=np.arange(11)
display(a)
(a>=4)&(a<10)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([False, False, False, False,  True,  True,  True,  True,  True,
        True, False])

In [49]:
a=np.arange(11)
display(a)
a[(a>=4)&(a<10)]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([4, 5, 6, 7, 8, 9])

In [52]:
a=np.arange(11)
display(a)
a[(a>=4)&(a<9)]=10
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([ 0,  1,  2,  3, 10, 10, 10, 10, 10,  9, 10])

In [54]:
n1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [57]:
n1[0:9:2,0:9:2]

array([[ 0,  2,  4,  6,  8],
       [20, 22, 24, 26, 28],
       [40, 42, 44, 46, 48],
       [60, 62, 64, 66, 68],
       [80, 82, 84, 86, 88]])

In [58]:
n1[::2,::2]

array([[ 0,  2,  4,  6,  8],
       [20, 22, 24, 26, 28],
       [40, 42, 44, 46, 48],
       [60, 62, 64, 66, 68],
       [80, 82, 84, 86, 88]])

In [64]:
n1[[0,2,4,6,-1],[-4,-1,0,6,1]]

array([ 6, 29, 40, 66, 91])

In [65]:
n1[[0,1,3,6,9]][::3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])