## Numpy

In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.24.3


In [3]:
##! pip install --upgrade numpy

In [4]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__git_version__',
 '__loader__',

In [5]:
l=[1,3,4,2,0]
np.sort(l)

array([0, 1, 2, 3, 4])

In [6]:
np.square(l)

array([ 1,  9, 16,  4,  0])

In [7]:
import numpy as np 
print(np.__version__)

1.24.3


## we are proving that numpy is faster than python

In [8]:
%%time
[i+5 for i in range(10000000)]

Wall time: 1.3 s


[5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 1

In [9]:
%%time 
np.arange(1000000)

Wall time: 2 ms


array([     0,      1,      2, ..., 999997, 999998, 999999])

In [10]:
np.arange(10)+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
 # a=[1,2,3]+5

In [12]:
np.array([1,2,3])+5

array([6, 7, 8])

## Easy to use (Simplicity)

In [13]:
l=[[1,2,3,10],
  [4,5,6,11],
  [7,8,9,12]]
print(l)

[[1, 2, 3, 10], [4, 5, 6, 11], [7, 8, 9, 12]]


In [14]:
for rid,row in enumerate(l):
    print(rid,row)
    for cid,_ in enumerate(row):
        print(cid,end="***")
    print()

0 [1, 2, 3, 10]
0***1***2***3***
1 [4, 5, 6, 11]
0***1***2***3***
2 [7, 8, 9, 12]
0***1***2***3***


In [15]:
for rid,row in enumerate(l):
    print(rid,row)
    for cid,_ in enumerate(row):
        l[rid][cid] +=5
l

0 [1, 2, 3, 10]
1 [4, 5, 6, 11]
2 [7, 8, 9, 12]


[[6, 7, 8, 15], [9, 10, 11, 16], [12, 13, 14, 17]]

In [16]:
l1=[[1,2,3,10],
  [4,5,6,11],
  [7,8,9,12]]
np.array(l1)

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

In [17]:
l1 + 5

TypeError: can only concatenate list (not "int") to list

# How we can create numpy array
* list 
* list of list
* tuple
* set 
 ## Functions used for creating numpy array
 * np.array()
 * np.asarray()
 * np.arange()

In [ ]:
l1=[1,2,3,4,5]
display(l1)
display(type(l1))

In [21]:
l1=np.array(l1)
display(l1)
display(type(l1))

print("dimesion:",l1.ndim)
print("size:",l1.size)
print("no access in each dimesion ",l1.shape)
print("data type",l1.dtype)

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

numpy.ndarray

dimesion: 2
size: 12
no access in each dimesion  (3, 4)
data type int32


In [22]:
l1=(1,2,3,4,5)
display(l1)
display(type(l1))
l1=np.array(l1)
display(l1)
display(type(l1))

print("dimesion:",l1.ndim)
print("size:",l1.size)
print("no access in each dimesion ",l1.shape)
print("data type",l1.dtype)

(1, 2, 3, 4, 5)

tuple

array([1, 2, 3, 4, 5])

numpy.ndarray

dimesion: 1
size: 5
no access in each dimesion  (5,)
data type int32


In [23]:
l1=[[1,2,3,10],
  [4,5,6,11],
  [7,8,9,12]]
display(l1)
display(type(l1))
l1=np.array(l1)
display(l1)
display(type(l1))

print("dimesion:",l1.ndim)
print("size:",l1.size)
print("no access in each dimesion ",l1.shape)
print("data type",l1.dtype)

[[1, 2, 3, 10], [4, 5, 6, 11], [7, 8, 9, 12]]

list

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

numpy.ndarray

dimesion: 2
size: 12
no access in each dimesion  (3, 4)
data type int32


In [24]:
# set obj type will not work smoothly there will be some error generated 

# Real World DAta 
 * scalar 
 * vector
 * matrics
 * n-dimension array

In [26]:
## 1) Scalar
l1=np.asarray(7)
display(l1)
display(type(l1))
l1=np.array(l1)
display(l1)
display(type(l1))

print("dimesion:",l1.ndim)
print("size:",l1.size)
print("no access in each dimesion ",l1.shape)
print("data type",l1.dtype)

array(7)

numpy.ndarray

array(7)

numpy.ndarray

dimesion: 0
size: 1
no access in each dimesion  ()
data type int32


In [27]:
## 1) Vector
l1=np.asarray([1,2,3])
display(l1)
display(type(l1))
l1=np.array(l1)
display(l1)
display(type(l1))

print("dimesion:",l1.ndim)
print("size:",l1.size)
print("no access in each dimesion ",l1.shape)
print("data type",l1.dtype)

array([1, 2, 3])

numpy.ndarray

array([1, 2, 3])

numpy.ndarray

dimesion: 1
size: 3
no access in each dimesion  (3,)
data type int32


In [28]:
## 1) Matrix
l1=np.asarray([[1,2,3]])
display(l1)
display(type(l1))
l1=np.array(l1)
display(l1)
display(type(l1))

print("dimesion:",l1.ndim)
print("size:",l1.size)
print("no access in each dimesion ",l1.shape)
print("data type",l1.dtype)

array([[1, 2, 3]])

numpy.ndarray

array([[1, 2, 3]])

numpy.ndarray

dimesion: 2
size: 3
no access in each dimesion  (1, 3)
data type int32


In [34]:
display(np.arange(1,4))

array([1, 2, 3])

In [35]:
l1 = np.arange(1,13).reshape((2,6))
print(l1)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [37]:
l1 = np.arange(1,13).reshape((6,2))
print(l1)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [38]:
l1 = np.arange(1,13).reshape((3,4))
print(l1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [39]:
l1 = np.arange(1,13).reshape((4,3))
print(l1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [40]:
print(l1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [48]:
l1 = np.arange(6*4).reshape((3,2,4))
l1
display(l1)
display(type(l1))
l1=np.array(l1)
display(l1)
display(type(l1))

print("dimesion:",l1.ndim)
print("size:",l1.size)
print("no access in each dimesion ",l1.shape)
print("data type",l1.dtype)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

numpy.ndarray

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

numpy.ndarray

dimesion: 3
size: 24
no access in each dimesion  (3, 2, 4)
data type int32


In [49]:
l1 = np.arange(6*4).reshape((3,2,4,1))
l1
display(l1)
display(type(l1))
l1=np.array(l1)
display(l1)
display(type(l1))

print("dimesion:",l1.ndim)
print("size:",l1.size)
print("no access in each dimesion ",l1.shape)
print("data type",l1.dtype)

array([[[[ 0],
         [ 1],
         [ 2],
         [ 3]],

        [[ 4],
         [ 5],
         [ 6],
         [ 7]]],


       [[[ 8],
         [ 9],
         [10],
         [11]],

        [[12],
         [13],
         [14],
         [15]]],


       [[[16],
         [17],
         [18],
         [19]],

        [[20],
         [21],
         [22],
         [23]]]])

numpy.ndarray

array([[[[ 0],
         [ 1],
         [ 2],
         [ 3]],

        [[ 4],
         [ 5],
         [ 6],
         [ 7]]],


       [[[ 8],
         [ 9],
         [10],
         [11]],

        [[12],
         [13],
         [14],
         [15]]],


       [[[16],
         [17],
         [18],
         [19]],

        [[20],
         [21],
         [22],
         [23]]]])

numpy.ndarray

dimesion: 4
size: 24
no access in each dimesion  (3, 2, 4, 1)
data type int32


In [50]:
l1 = np.arange(6*4).reshape((3,2,4,1,1))
l1
display(l1)
display(type(l1))
l1=np.array(l1)
display(l1)
display(type(l1))

print("dimesion:",l1.ndim)
print("size:",l1.size)
print("no access in each dimesion ",l1.shape)
print("data type",l1.dtype)

array([[[[[ 0]],

         [[ 1]],

         [[ 2]],

         [[ 3]]],


        [[[ 4]],

         [[ 5]],

         [[ 6]],

         [[ 7]]]],



       [[[[ 8]],

         [[ 9]],

         [[10]],

         [[11]]],


        [[[12]],

         [[13]],

         [[14]],

         [[15]]]],



       [[[[16]],

         [[17]],

         [[18]],

         [[19]]],


        [[[20]],

         [[21]],

         [[22]],

         [[23]]]]])

numpy.ndarray

array([[[[[ 0]],

         [[ 1]],

         [[ 2]],

         [[ 3]]],


        [[[ 4]],

         [[ 5]],

         [[ 6]],

         [[ 7]]]],



       [[[[ 8]],

         [[ 9]],

         [[10]],

         [[11]]],


        [[[12]],

         [[13]],

         [[14]],

         [[15]]]],



       [[[[16]],

         [[17]],

         [[18]],

         [[19]]],


        [[[20]],

         [[21]],

         [[22]],

         [[23]]]]])

numpy.ndarray

dimesion: 5
size: 24
no access in each dimesion  (3, 2, 4, 1, 1)
data type int32


## Generating RGB Slide

In [55]:
img=np.random.randint(0,25,size=(5,5,3))
img

array([[[ 9, 11, 22],
        [ 9, 24, 15],
        [21, 17, 13],
        [17, 16, 24],
        [13,  3, 16]],

       [[24,  6, 14],
        [12,  3,  8],
        [ 6,  3, 21],
        [ 0, 18,  4],
        [21, 23, 23]],

       [[11, 12, 10],
        [ 0, 10, 12],
        [13,  5,  0],
        [ 2, 16,  9],
        [12, 10, 10]],

       [[ 8,  4, 23],
        [15, 10,  3],
        [ 2, 10,  5],
        [13, 17, 12],
        [ 1, 17, 20]],

       [[ 0, 18, 15],
        [22, 21, 10],
        [12, 19,  7],
        [20,  5, 22],
        [13,  1, 17]]])