In [3]:
import numpy as np
import cv2

In [12]:
image1 = cv2.imread('./images.jpg')
image2 = cv2.imread('./istockphoto-1157655660-612x612.jpg')

image1 = cv2.resize(image1, (1000, 1000))
image2 = cv2.resize(image2, (1000, 1000))
result = np.add(image1, image2)

In [7]:
cv2.imshow('Result', result)

In [8]:
print(result)

[[[250 240 223]
  [250 240 223]
  [251 243 226]
  ...
  [ 12  77  32]
  [  6  70  28]
  [ 13  72  34]]

 [[250 240 224]
  [248 238 221]
  [246 237 222]
  ...
  [  7  71  27]
  [  3  63  22]
  [  6  65  27]]

 [[251 241 227]
  [248 239 222]
  [243 234 220]
  ...
  [  3  65  22]
  [255  56  15]
  [  0  56  18]]

 ...

 [[134 144 149]
  [137 147 152]
  [139 150 155]
  ...
  [140 148 148]
  [139 147 147]
  [138 146 146]]

 [[132 143 147]
  [135 146 150]
  [138 149 153]
  ...
  [138 146 146]
  [137 145 145]
  [136 144 144]]

 [[131 142 146]
  [134 145 149]
  [137 148 152]
  ...
  [137 145 145]
  [136 144 144]
  [135 143 143]]]


In [ ]:
cv2.imshow('Result', result)
cv2.waitKey(0)
cv2.destroyAllWindows()

cv2.imwrite('result.jpg', result)

In [15]:
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

image1 = np.array(Image.open('./images.jpg'))
image2 = np.array(Image.open('./istockphoto-1157655660-612x612.jpg'))
width, height = 1000, 1000
image1 = np.resize(image1, (height, width))
image2 = np.resize(image2, (height, width))
result = np.add(image1, image2)
plt.imshow(result)
plt.axis('off')
plt.show()

result_image = Image.fromarray(result.astype(np.uint8))
result_image.save('result.jpg')
