In [2]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [4]:
l = ["a","b","c"]
display(type(l))
display(l)

list

['a', 'b', 'c']

In [5]:
l = np.array(["a","b","c"])
display(type(l))
display(l)

numpy.ndarray

array(['a', 'b', 'c'], dtype='<U1')

## Series Data Type in Pandas

In [6]:
l = pd.Series(["a","b","c"])
display(type(l))
display(l)

pandas.core.series.Series

0    a
1    b
2    c
dtype: object

In [8]:
l=[[1,2,3],
  [4,5,6],
  [7,8,9]]
display(type(l))
display(l)

list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
l=np.array([[1,2,3],
  [4,5,6],
  [7,8,9]])
display(type(l))
display(l)

numpy.ndarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Pandas Data Frame

In [12]:
l=pd.DataFrame([[1,2,3],
  [4,5,6],
  [7,8,9]])
display(type(l))
display(l)

pandas.core.frame.DataFrame

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

## How we can create Series in pandas ??
* list 
* tuple
* list for index and list for values
* dictionary

In [16]:
l=list("ABDJDFHFFHKFHAUFHFUURRU")
display(type(l))
display(l)

l=pd.Series(l)
display(type(l))
display(l)

list

['A',
 'B',
 'D',
 'J',
 'D',
 'F',
 'H',
 'F',
 'F',
 'H',
 'K',
 'F',
 'H',
 'A',
 'U',
 'F',
 'H',
 'F',
 'U',
 'U',
 'R',
 'R',
 'U']

pandas.core.series.Series

0     A
1     B
2     D
3     J
4     D
5     F
6     H
7     F
8     F
9     H
10    K
11    F
12    H
13    A
14    U
15    F
16    H
17    F
18    U
19    U
20    R
21    R
22    U
dtype: object

In [17]:
l=tuple("ABDJDFHFFHKFHAUFHFUURRU")
display(type(l))
display(l)

l=pd.Series(l)
display(type(l))
display(l)

tuple

('A',
 'B',
 'D',
 'J',
 'D',
 'F',
 'H',
 'F',
 'F',
 'H',
 'K',
 'F',
 'H',
 'A',
 'U',
 'F',
 'H',
 'F',
 'U',
 'U',
 'R',
 'R',
 'U')

pandas.core.series.Series

0     A
1     B
2     D
3     J
4     D
5     F
6     H
7     F
8     F
9     H
10    K
11    F
12    H
13    A
14    U
15    F
16    H
17    F
18    U
19    U
20    R
21    R
22    U
dtype: object

In [18]:
l = {
    "a":"Pakistan",
    "b":"China",
    "c":"India"
}
display(type(l))
display(l)

l=pd.Series(l)
display(type(l))
display(l)

dict

{'a': 'Pakistan', 'b': 'China', 'c': 'India'}

pandas.core.series.Series

a    Pakistan
b       China
c       India
dtype: object

In [21]:
i = ["A","B","C"]
v = [100,200,300]

l= pd.Series(v,i)
l=pd.Series(data=v,index=i)
display(l)

A    100
B    200
C    300
dtype: int64

In [26]:
n = np.random.randint(1,100,10)
display(n)
pd.Series(n,name="abcd",dtype=np.int64)

array([ 6, 77, 65, 75, 77, 10, 30, 67, 14, 48])

0     6
1    77
2    65
3    75
4    77
5    10
6    30
7    67
8    14
9    48
Name: abcd, dtype: int64

## How can we create DataFrame in Pandas ??
* Matrics 
* list of list 
* tuple of tuple 
* dictionary 
* 2-D Array 
* DataFrame Attributes 
     * dtype 
     * shape

In [28]:
l=[[1,2,3],
  [4,5,6],
  [7,8,9]]
df = pd.DataFrame(l)
display(df)

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [29]:
l=((1,2,3),
  (4,5,6),
  (7,8,9))
df = pd.DataFrame(l)
display(df)

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [30]:
l=[[1,2,3],
  [4,5,6],
  [7,8,9]]

n = np.array(l)
df=pd.DataFrame(n)
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [33]:
l=[[1,2,3],
  [4,5,6],
  [7,8,9]]

n = np.array(l)
df=pd.DataFrame(n,columns=["id","name","cnic"],
                  index = ["a","b","c"])
df

id  name  cnic
a   1     2     3
b   4     5     6
c   7     8     9

## Data Frame Components 
* column index
* row index
* values

In [39]:
l=[[1,2,3],
  [4,5,6],
  [7,8,9]]

n = np.array(l)
df=pd.DataFrame(n,columns=["id","name","cnic"],
                  index = ["a","b","c"])
display(df.columns)
display(df.index)
display(df.values)

Index(['id', 'name', 'cnic'], dtype='object')

Index(['a', 'b', 'c'], dtype='object')

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])